### Prueba de limpieza partiendo el dataframe por Estación

In [1]:
import pandas as pd

In [4]:
dataCompleto = pd.read_csv('estaciones_combinadas_NO_LIMPIO.csv', decimal=",")
dataCompleto

,COD_ESTACION,NOM_ESTACION,FECHA,HORA,SO2,CO,NO,NO2,NOx,O3,...,BkFA,Cd,DahA,FA,HMN,H2S,IcdP,Ni,Pb,PST
0,3065006,ELX - AGROALIMENTARI,2020-01-01,0,3,"0,1",2,16,18,22,...,-,-,-,-,-,-,-,-,-,-
1,3065006,ELX - AGROALIMENTARI,2020-01-01,1,3,"0,1",2,28,31,14,...,-,-,-,-,-,-,-,-,-,-
2,3065006,ELX - AGROALIMENTARI,2020-01-01,2,3,"0,1",2,18,20,20,...,-,-,-,-,-,-,-,-,-,-
3,3065006,ELX - AGROALIMENTARI,2020-01-01,3,3,"0,1",2,19,21,12,...,-,-,-,-,-,-,-,-,-,-
4,3065006,ELX - AGROALIMENTARI,2020-01-01,4,3,"0,1",2,15,17,7,...,-,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74587,3133002,TORREVIEJA,2024-11-30,19,-,-,16,59,83,6,...,-,-,-,-,-,-,-,-,-,-
74588,3133002,TORREVIEJA,2024-11-30,20,-,-,35,57,111,3,...,-,-,-,-,-,-,-,-,-,-
74589,3133002,TORREVIEJA,2024-11-30,21,-,-,21,47,79,3,...,-,-,-,-,-,-,-,-,-,-
74590,3133002,TORREVIEJA,2024-11-30,22,-,-,13,30,49,5,...,-,-,-,-,-,-,-,-,-,-
74591,3133002,TORREVIEJA,2024-11-30,23,-,-,9,21,35,7,...,-,-,-,-,-,-,-,-,-,-

In [5]:
dataElche = dataCompleto[dataCompleto["NOM_ESTACION"] == "ELX - AGROALIMENTARI"]
dataTorrevieja = dataCompleto[dataCompleto["NOM_ESTACION"] == "TORREVIEJA"]
dataOrihuela = dataCompleto[dataCompleto["NOM_ESTACION"] == "ORIHUELA"]

In [17]:
def limpiezaAutomaticaPorEstacion(dataFrame):
    dataFrame.replace("-", pd.NA, inplace=True)
    columnasImportantes = [
        'COD_ESTACION', 'NOM_ESTACION', 'FECHA', 'HORA', 'SO2', 'CO', 'NO', 'NO2',
    'NOx', 'O3',
    ]
    
    dataFrame = dataFrame[columnasImportantes]
    
    columnas_con_nulos = ['SO2', 'NO', 'NO2', 'NOx', 'O3']
    
    for columna in columnas_con_nulos:
            dataFrame[columna] = pd.to_numeric(dataFrame[columna], errors='coerce')
            
    for columna in columnas_con_nulos:
        dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)
        
    dataFrame = dataFrame.dropna(axis = 1, thresh = 0.5 * len(dataFrame) * 0.5)
        
    return dataFrame

In [20]:
limpiezaAutomaticaPorEstacion(dataElche)

C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame.replace("-", pd.NA, inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame[columna] = pd.to_numeric(dataFrame[columna], errors='coerce')
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)

,COD_ESTACION,NOM_ESTACION,FECHA,HORA,SO2,CO,NO,NO2,NOx,O3
0,3065006,ELX - AGROALIMENTARI,2020-01-01,0,3.0,"0,1",2.0,16.0,18.0,22.0
1,3065006,ELX - AGROALIMENTARI,2020-01-01,1,3.0,"0,1",2.0,28.0,31.0,14.0
2,3065006,ELX - AGROALIMENTARI,2020-01-01,2,3.0,"0,1",2.0,18.0,20.0,20.0
3,3065006,ELX - AGROALIMENTARI,2020-01-01,3,3.0,"0,1",2.0,19.0,21.0,12.0
4,3065006,ELX - AGROALIMENTARI,2020-01-01,4,3.0,"0,1",2.0,15.0,17.0,7.0
...,...,...,...,...,...,...,...,...,...,...
73147,3065006,ELX - AGROALIMENTARI,2024-11-30,19,4.0,"0,1",2.0,5.0,7.0,58.0
73148,3065006,ELX - AGROALIMENTARI,2024-11-30,20,4.0,"0,1",2.0,6.0,8.0,61.0
73149,3065006,ELX - AGROALIMENTARI,2024-11-30,21,4.0,"0,1",2.0,9.0,11.0,55.0
73150,3065006,ELX - AGROALIMENTARI,2024-11-30,22,4.0,"0,1",1.0,16.0,18.0,38.0
73151,3065006,ELX - AGROALIMENTARI,2024-11-30,23,4.0,"0,1",2.0,18.0,21.0,25.0

In [19]:
limpiezaAutomaticaPorEstacion(dataTorrevieja)

C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame.replace("-", pd.NA, inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame[columna] = pd.to_numeric(dataFrame[columna], errors='coerce')
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)

       COD_ESTACION NOM_ESTACION       FECHA  HORA    NO   NO2    NOx    O3
1488        3133002   TORREVIEJA  2020-01-01     0  30.0  40.0   86.0   7.0
1489        3133002   TORREVIEJA  2020-01-01     1  67.0  51.0  154.0   6.0
1490        3133002   TORREVIEJA  2020-01-01     2  45.0  45.0  113.0   5.0
1491        3133002   TORREVIEJA  2020-01-01     3  43.0  39.0  105.0   4.0
1492        3133002   TORREVIEJA  2020-01-01     4   3.0  11.0   17.0  22.0
...             ...          ...         ...   ...   ...   ...    ...   ...
74587       3133002   TORREVIEJA  2024-11-30    19  16.0  59.0   83.0   6.0
74588       3133002   TORREVIEJA  2024-11-30    20  35.0  57.0  111.0   3.0
74589       3133002   TORREVIEJA  2024-11-30    21  21.0  47.0   79.0   3.0
74590       3133002   TORREVIEJA  2024-11-30    22  13.0  30.0   49.0   5.0
74591       3133002   TORREVIEJA  2024-11-30    23   9.0  21.0   35.0   7.0

[24864 rows x 8 columns]

In [16]:
dataTorrevieja

,COD_ESTACION,NOM_ESTACION,FECHA,HORA,SO2,CO,NO,NO2,NOx,O3,...,BkFA,Cd,DahA,FA,HMN,H2S,IcdP,Ni,Pb,PST
1488,3133002,TORREVIEJA,2020-01-01,0,<NA>,<NA>,30,40,86,7,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1489,3133002,TORREVIEJA,2020-01-01,1,<NA>,<NA>,67,51,154,6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1490,3133002,TORREVIEJA,2020-01-01,2,<NA>,<NA>,45,45,113,5,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1491,3133002,TORREVIEJA,2020-01-01,3,<NA>,<NA>,43,39,105,4,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1492,3133002,TORREVIEJA,2020-01-01,4,<NA>,<NA>,3,11,17,22,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74587,3133002,TORREVIEJA,2024-11-30,19,<NA>,<NA>,16,59,83,6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
74588,3133002,TORREVIEJA,2024-11-30,20,<NA>,<NA>,35,57,111,3,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
74589,3133002,TORREVIEJA,2024-11-30,21,<NA>,<NA>,21,47,79,3,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
74590,3133002,TORREVIEJA,2024-11-30,22,<NA>,<NA>,13,30,49,5,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
74591,3133002,TORREVIEJA,2024-11-30,23,<NA>,<NA>,9,21,35,7,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [21]:
conjuntoDatos = [dataElche, dataTorrevieja, dataOrihuela]

In [22]:
for dataFrame in conjuntoDatos:
    limpiezaAutomaticaPorEstacion(dataFrame)

C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame.replace("-", pd.NA, inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame[columna] = pd.to_numeric(dataFrame[columna], errors='coerce')
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame.replace("-", pd.NA, inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame[columna] = pd.to_numeric(dataFrame[columna], errors='coerce')
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame.replace("-", pd.NA, inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame[columna] = pd.to_numeric(dataFrame[columna], errors='coerce')
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)
C:\Users\javgomdav\AppData\Local\Temp\ipykernel_14484\3565068501.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame[columna].fillna(dataFrame[columna].mean(), inplace=True)

In [26]:
import json

In [31]:
def dataFrametoJSON(dataFrame, nombre):
    json_object = dataFrame.to_json(orient='records')
    filename = f"{nombre}-LIMPIO.json"
    with open(filename, 'w') as file:
        file.write(json_object)
    print(f"Archivo guardado como {filename}")

In [32]:
dataFrametoJSON(dataElche, "Elche")
dataFrametoJSON(dataOrihuela, "Orihuela")
dataFrametoJSON(dataTorrevieja, "Torrevieja")

Archivo guardado como Elche-LIMPIO.json
Archivo guardado como Orihuela-LIMPIO.json
Archivo guardado como Torrevieja-LIMPIO.json

In [33]:
import streamlit as st

In [34]:
st.write(dataElche.head(10))

2025-01-22 20:04:27.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-22 20:04:27.953
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\javgomdav\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-01-22 20:04:27.954 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.